import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CursorGlow from "@/components/CursorGlow";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

      <CursorGlow />
        {children}
      <Footer />
      {/* 🔥 Toasts */}
      <Toaster
          position="top-right"
          toastOptions={{
            style: {
              background: "#0a0a0f",
              color: "#fff",
              border: "1px solid #ffffff22",
              boxShadow: "0 0 15px #00eaff",
            },
          }}
      />
      </body>
    </html>
  );
}
